package proyecto;

import java.awt.Color;

/**
 *
 * @author 18PROGB0073
 */
public class Inicio extends javax.swing.JFrame {

    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.darkGray);
        this.setDefaultCloseOperation(Inicio.DO_NOTHING_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        lbl002 = new javax.swing.JLabel();
        lbl001 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSistemaNervioso = new javax.swing.JTextArea();
        label1 = new java.awt.Label();
        btnSalir = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNeuronas = new javax.swing.JMenu();
        mniPartes = new javax.swing.JMenuItem();
        mniFunciones = new javax.swing.JMenuItem();
        mniCarac = new javax.swing.JMenuItem();
        mnuCelulasGliales = new javax.swing.JMenu();
        mniSchwann = new javax.swing.JMenuItem();
        mniOli = new javax.swing.JMenuItem();
        mniMicroglia = new javax.swing.JMenuItem();
        mniAstrocitos = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        lbl002.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen002.jpg"))); // NOI18N

        lbl001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen001.jpg"))); // NOI18N

        txaSistemaNervioso.setEditable(false);
        txaSistemaNervioso.setBackground(new java.awt.Color(102, 102, 102));
        txaSistemaNervioso.setColumns(20);
        txaSistemaNervioso.setForeground(new java.awt.Color(255, 255, 255));
        txaSistemaNervioso.setLineWrap(true);
        txaSistemaNervioso.setRows(5);
        txaSistemaNervioso.setText("¿Qué tipos de células son existentes dentro del sistema nervioso?\n\nEn el sistema nervioso son existentes dos tipos de células las cuales son las neuronas que tienen la capacidad de comunicarse con precisión, rapidez y a larga distancia con otras células, ya sean nerviosas, musculares o glandulares. A través de las neuronas se transmiten señales eléctricas denominadas impulsos nerviosos. La conexión entre una neurona y otra se denomina sinapsis. También son existentes las células de glial o células gliales que desempeñan, de forma principal, la función de soporte de las neuronas; además intervienen activamente en el procesamiento cerebral de la información en el organismo.\n");
        txaSistemaNervioso.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaSistemaNervioso);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(0, 102, 102));
        label1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Células del Sistema Nervioso");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAcercaDe.setText("Acerca de");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        mnuNeuronas.setText("Neuronas");
        mnuNeuronas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNeuronasActionPerformed(evt);
            }
        });

        mniPartes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniPartes.setText("Partes de la neurona ");
        mniPartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPartesActionPerformed(evt);
            }
        });
        mnuNeuronas.add(mniPartes);

        mniFunciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniFunciones.setText("Funciones de la neurona ");
        mniFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFuncionesActionPerformed(evt);
            }
        });
        mnuNeuronas.add(mniFunciones);

        mniCarac.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniCarac.setText("Caracterisiticas Morfologicas de la Neurona ");
        mniCarac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCaracActionPerformed(evt);
            }
        });
        mnuNeuronas.add(mniCarac);

        jMenuBar1.add(mnuNeuronas);

        mnuCelulasGliales.setText("Celulas gliales");

        mniSchwann.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniSchwann.setText("Celulas de Schwann");
        mniSchwann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSchwannActionPerformed(evt);
            }
        });
        mnuCelulasGliales.add(mniSchwann);

        mniOli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniOli.setText("Oligondedrocitos");
        mniOli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOliActionPerformed(evt);
            }
        });
        mnuCelulasGliales.add(mniOli);

        mniMicroglia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniMicroglia.setText("Microglía");
        mniMicroglia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMicrogliaActionPerformed(evt);
            }
        });
        mnuCelulasGliales.add(mniMicroglia);

        mniAstrocitos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniAstrocitos.setText("Astrocitos");
        mniAstrocitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAstrocitosActionPerformed(evt);
            }
        });
        mnuCelulasGliales.add(mniAstrocitos);

        jMenuBar1.add(mnuCelulasGliales);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl002)
                        .addGap(44, 44, 44)
                        .addComponent(lbl001))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAcercaDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl002)
                    .addComponent(lbl001, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(btnAcercaDe))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFuncionesActionPerformed
        FrmFncnsNeurona mniPartes = new FrmFncnsNeurona();
        mniPartes.setVisible(true);
    }//GEN-LAST:event_mniFuncionesActionPerformed

    private void mniCaracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCaracActionPerformed
        FrmCaracMorNeurona mniPartes = new FrmCaracMorNeurona();
        mniPartes.setVisible(true);
    }//GEN-LAST:event_mniCaracActionPerformed

    private void mniPartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPartesActionPerformed
        FrmPrtNeurona mniPartes = new FrmPrtNeurona();
        mniPartes.setVisible(true);
    }//GEN-LAST:event_mniPartesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mnuNeuronasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNeuronasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNeuronasActionPerformed

    private void mniSchwannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSchwannActionPerformed
        FrmCelSchwann mniPartes = new FrmCelSchwann();
        mniPartes.setVisible(true);
    }//GEN-LAST:event_mniSchwannActionPerformed

    private void mniOliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOliActionPerformed
        FrmOli mniPartes = new FrmOli();
        mniPartes.setVisible(true);
    }//GEN-LAST:event_mniOliActionPerformed

    private void mniMicrogliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMicrogliaActionPerformed
        FrmMicroglia mniPartes = new FrmMicroglia();
        mniPartes.setVisible(true);
    }//GEN-LAST:event_mniMicrogliaActionPerformed

    private void mniAstrocitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAstrocitosActionPerformed
        FrmAstrocitos mniPartes = new FrmAstrocitos();
        mniPartes.setVisible(true);
    }//GEN-LAST:event_mniAstrocitosActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        FrmAcercaDe btnAcercaDe = new FrmAcercaDe();
        btnAcercaDe.setVisible(true);
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lbl001;
    private javax.swing.JLabel lbl002;
    private javax.swing.JMenuItem mniAstrocitos;
    private javax.swing.JMenuItem mniCarac;
    private javax.swing.JMenuItem mniFunciones;
    private javax.swing.JMenuItem mniMicroglia;
    private javax.swing.JMenuItem mniOli;
    private javax.swing.JMenuItem mniPartes;
    private javax.swing.JMenuItem mniSchwann;
    private javax.swing.JMenu mnuCelulasGliales;
    private javax.swing.JMenu mnuNeuronas;
    private javax.swing.JTextArea txaSistemaNervioso;
    // End of variables declaration//GEN-END:variables
}
